name: base_pm2
description: A base application.


publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  fluttertoast: ^8.0.7
  retrofit: ^2.0.0
  logger: ^1.0.0
  shared_preferences: ^2.0.6
  intl: ^0.17.0
  get: ^4.1.4
  flutter_svg: ^0.22.0
  cached_network_image: ^3.0.0
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  firebase_messaging: ^10.0.4
  firebase_remote_config: ^0.10.0+3
  flutter_local_notifications: ^8.0.0
  flutter_html: ^2.0.0
  url_launcher: ^6.0.7
  syncfusion_flutter_datepicker: ^19.2.56
  pull_to_refresh: ^2.0.0
  flutter_typeahead: ^3.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^2.0.0+1
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0


flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/